name: Debug Test

on:
  workflow_call:
    inputs:
      Name:
      required: false
      description: Name yourself

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: demo workflow job
        run: echo This is a ${{ inputs.Name }}
